singleServerConfig:
  address: "redis://127.0.0.1:6379"
  connectionMinimumIdleSize: 1
  connectionPoolSize: 10
  idleConnectionTimeout: 10000
  timeout: 3000
threads: 4
nettyThreads: 4
codec: !<org.redisson.codec.JsonJacksonCodec> {}
